use crate::changelog::VersionEntry;
use crate::summarizer::Summary;

use super::domain::{FormatError, Message, SummaryFormatter};

pub struct MarkdownSummaryFormatter;

impl SummaryFormatter for MarkdownSummaryFormatter {
    fn format(&self, items: &[(VersionEntry, Summary)]) -> Result<Message, FormatError> {
        if items.is_empty() {
            return Err(FormatError::NoEntries);
        }

        let newest = &items[0].0.version;
        let oldest = &items[items.len() - 1].0.version;
        let count = items.len();

        let version_range = if count == 1 {
            format!("{newest}")
        } else {
            format!("{oldest} → {newest}")
        };

        let plural = if count == 1 { "" } else { "s" };

        let mut body = String::new();
        for (entry, summary) in items {
            body.push_str(&format!("*{}*\n\n{}\n\n", entry.version, summary.text));
        }

        let text = format!(
            "*Claude Code Update — {version_range} ({count} new version{plural})*\n\
             \n\
             ---\n\
             \n\
             [Changelog](https://github.com/anthropics/claude-code/releases)\n\
             \n\
             {body}\
             ---\n\
             *Generated by [claudesynth](https://github.com/giorgiovilardo/claudesynth)*",
        );

        Ok(Message { text })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helpers::{summary, version_entry as entry};

    #[test]
    fn format_single_entry() {
        let formatter = MarkdownSummaryFormatter;
        let items = vec![(entry("2.1.78", "stuff"), summary("- New feature"))];
        let msg = formatter.format(&items).unwrap();
        assert!(msg.text.contains("2.1.78"));
        assert!(msg.text.contains("1 new version)"));
        assert!(msg.text.contains("- New feature"));
        assert!(
            msg.text
                .contains("[Changelog](https://github.com/anthropics/claude-code/releases)")
        );
    }

    #[test]
    fn format_multiple_entries() {
        let formatter = MarkdownSummaryFormatter;
        let items = vec![
            (entry("2.1.78", "a"), summary("- Feature")),
            (entry("2.1.77", "b"), summary("- Fix")),
            (entry("2.1.76", "c"), summary("- Tweak")),
        ];
        let msg = formatter.format(&items).unwrap();
        assert!(msg.text.contains("2.1.76 → 2.1.78"));
        assert!(msg.text.contains("3 new versions)"));
    }

    #[test]
    fn format_includes_per_version_headings() {
        let formatter = MarkdownSummaryFormatter;
        let items = vec![
            (entry("2.1.78", "a"), summary("- Feature X")),
            (entry("2.1.77", "b"), summary("- Fix Y")),
        ];
        let msg = formatter.format(&items).unwrap();
        assert!(msg.text.contains("*2.1.78*"));
        assert!(msg.text.contains("*2.1.77*"));
        assert!(msg.text.contains("- Feature X"));
        assert!(msg.text.contains("- Fix Y"));
    }

    #[test]
    fn format_message_structure() {
        let formatter = MarkdownSummaryFormatter;
        let items = vec![(entry("2.1.78", "stuff"), summary("- Some change"))];
        let msg = formatter.format(&items).unwrap();
        let header_pos = msg.text.find("*Claude Code Update").unwrap();
        let separator_pos = msg.text.find("---").unwrap();
        let link_pos = msg.text.find("[Changelog]").unwrap();
        let summary_pos = msg.text.find("- Some change").unwrap();
        let footer_pos = msg.text.find("*Generated by").unwrap();
        assert!(header_pos < separator_pos);
        assert!(separator_pos < link_pos);
        assert!(link_pos < summary_pos);
        assert!(summary_pos < footer_pos);
    }

    #[test]
    fn format_rejects_no_entries() {
        let formatter = MarkdownSummaryFormatter;
        assert!(formatter.format(&[]).is_err());
    }
}
